replicaCount: 1

image:
  repository: ghcr.io/sriniboosaraju/myapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"

resources: {}
