# Staging environment overrides
replicaCount: 2
image:
  repository: ghcr.io/sriniboosaraju/myapp
  tag: "004829c"
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 80
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "automation:destroy-date=2026-12-31,environment=staging"
env:
  - name: NODE_ENV
    value: "staging"
  - name: LOG_LEVEL
    value: "info"
  - name: APP_NAME
    value: "myapp-staging"
  - name: REGION
    value: "us-east-1"
